variables:
  #azure variables
  FILEMETADATA_AZURE_SERVICE: seismic-dms-file-metadata-service
  CHART_PATH: devops/azure/chart
  CLOUD_PROVIDER: azure
  POD_IDENTITY: osdu-identity

filemetadata_azure_containerize:
  extends: .azure_containerize
  variables:
    SHA_IMAGE: ${FILEMETADATA_LOCAL_SERVICE_NAME}:${CI_COMMIT_SHA}
    LATEST_IMAGE: ${FILEMETADATA_LOCAL_SERVICE_NAME}:latest
    RELEASE_IMAGE: release-${CI_COMMIT_TAG}:${FILEMETADATA_LOCAL_SERVICE_NAME}-${CI_COMMIT_TAG}
  script:
    - cd app/$FILEMETADATA_SERVICE
    - sed -i "s/SEGY_LIBRARY_PAT/$SEGY_LIBRARY_FEED_PAT/g" pip.conf
    - docker build -t $FILEMETADATA_LOCAL_SERVICE_NAME --file devops/azure/Dockerfile .
    # Gitlab Container Registry
    - docker tag $FILEMETADATA_LOCAL_SERVICE_NAME $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker push ${CI_REGISTRY_IMAGE}/$SHA_IMAGE
    - docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE $CI_REGISTRY_IMAGE/$LATEST_IMAGE
    - docker push ${CI_REGISTRY_IMAGE}/$LATEST_IMAGE
    # Azure Container Registry
    - az acr login -n $AZURE_REGISTRY
    - docker tag $FILEMETADATA_LOCAL_SERVICE_NAME ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE
    - docker push ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE
    - docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE
    - docker push ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE
    - |
      if [ ! -z "$CI_COMMIT_TAG" ]; then
        docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
        docker push ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
      fi
  only:
    changes:
      - devops/**/*
      - app/filemetadata/**/*
    refs:
      - branches
      - main
      - merge_requests

filemetadata_azure_deploy:
  extends: .azure_deploy
  needs: ["filemetadata_azure_containerize"]
  variables:
    AZURE_KEYVAULT: osdu-svc-properties
    DES_URL: ${AZURE_DNS_NAME}
    IMAGE: ${AZURE_REGISTRY}.azurecr.io/${FILEMETADATA_LOCAL_SERVICE_NAME}
    FILEMETADATA_SERVICE_NAME: ${FILEMETADATA_AZURE_SERVICE}
    TAG: ${CI_COMMIT_SHA}
  script:
    # Replace values in config file
    - cd app/$FILEMETADATA_SERVICE
    - cp ${CHART_PATH}/helm-config.yaml ${CHART_PATH}/values.yaml
    - sed -i 's,#{CONTAINER_REGISTRY_NAME}#,'$IMAGE',' ${CHART_PATH}/values.yaml
    - sed -i 's,#{DNS_HOST}#,'$DES_URL',' ${CHART_PATH}/values.yaml
    - sed -i 's/#{ENVIRONMENT_NAME}#/'$ENVIRONMENT'/' ${CHART_PATH}/values.yaml
    - sed -i 's/#{IMAGE_TAG}#/'$TAG'/' ${CHART_PATH}/values.yaml
    - sed -i 's/#{KEYVAULT_NAME}#/'$AZURE_KEYVAULT'/' ${CHART_PATH}/values.yaml
    - sed -i 's/#{PROVIDER_NAME}#/'$CLOUD_PROVIDER'/' ${CHART_PATH}/values.yaml
    - sed -i 's/#{REPLICA_COUNT}#/'$REPLICA'/' ${CHART_PATH}/values.yaml
    - sed -i 's/#{MIN_REPLICA_COUNT}#/'$FILEMETADATA_MIN_REPLICA_COUNT'/' ${CHART_PATH}/values.yaml
    - sed -i 's/#{MAX_REPLICA_COUNT}#/'$FILEMETADATA_MAX_REPLICA_COUNT'/' ${CHART_PATH}/values.yaml
    # Install helm chart
    - helm upgrade $FILEMETADATA_AZURE_SERVICE ${CHART_PATH} --install --dry-run --values $CHART_PATH/values.yaml 
    - helm upgrade $FILEMETADATA_AZURE_SERVICE ${CHART_PATH} --install --values $CHART_PATH/values.yaml 
    # Wait for service to be running to start
    - kubectl rollout status deployment.v1.apps/$FILEMETADATA_SERVICE_NAME -n osdu --timeout=900s
    - pod=$(kubectl get pod -n osdu|grep $FILEMETADATA_LOCAL_SERVICE_NAME |tail -1 |awk '{print $1}')
    - status=$(kubectl wait -n osdu --for=condition=Ready pod/$pod --timeout=600s)
    - if [[ "$status" != *"met"* ]]; then echo "POD didn't start correctly" ; exit 1 ; fi
  only:
    changes:
      - devops/**/*
      - app/filemetadata/**/*
    refs:
      - branches
      - main
      - merge_requests

filemetadata_azure_unit_test:
  image: node
  extends: .azure_test
  stage: integration
  needs: ["filemetadata_azure_deploy"]
  variables:
    AZURE_AD_APP_RESOURCE_ID: $AZURE_APP_ID
    AZURE_AD_TENANT_ID: $AZURE_TENANT_ID
    AZURE_TESTER_SERVICEPRINCIPAL_SECRET: $AZURE_PRINCIPAL_SECRET
    INTEGRATION_TESTER: $AZURE_PRINCIPAL_ID
    DNS: https://${AZURE_DNS_NAME}
  script:
    - pip3 install requests msal fastapi python-dotenv
    - cd app/$FILEMETADATA_SERVICE/app
    - python3 -m unittest discover -s test -p test_* -v
  only:
    changes:
      - devops/**/*
      - app/filemetadata/**/*
    refs:
      - branches
      - main
      - merge_requests

filemetadata_azure_integration_test:
  image: node
  extends: .azure_test
  stage: integration
  needs: ["filemetadata_azure_deploy"]
  variables:
    AZURE_AD_APP_RESOURCE_ID: $AZURE_APP_ID
    AZURE_AD_TENANT_ID: $AZURE_TENANT_ID
    AZURE_TESTER_SERVICEPRINCIPAL_SECRET: $AZURE_PRINCIPAL_SECRET
    INTEGRATION_TESTER: $AZURE_PRINCIPAL_ID
    DNS: https://${AZURE_DNS_NAME}
  script:
    - pip3 install pytest requests msal
    - cd app/$FILEMETADATA_SERVICE/app
    - python3 -m pytest --traceconfig integration_test/
  only:
    changes:
      - devops/**/*
      - app/filemetadata/**/*
    refs:
      - branches
      - main
      - merge_requests
