# Service Config
image: __CONTAINER__
imagePullPolicy: Always
service:
  type: ClusterIP
  port: 8080
  apiPath: /api/seismic-store/v3
  readinessProbeHttpPath: /api/seismic-store/v3/svcstatus
  livenessProbeHttpPath: /api/seismic-store/v3/svcstatus
environmentVariables:
  - name: PORT
    value: "{{ .Values.service.port }}"
  - name: AWS_REGION
    value: "{{ .Values.global.region }}"
  - name: ENVIRONMENT
    value: "{{ .Values.global.resourcePrefix }}"
  - name: LOG_LEVEL
    value: "{{ default `INFO` .Values.global.logLevel }}"
  - name: SSM_ENABLED
    value: "True"
  - name: SSL_ENABLED
    value: "false"
  - name: LOCKSMAP_REDIS_INSTANCE_ADDRESS
    value: "{{ .Values.global.cacheClusterEndpoint }}"
  - name: LOCKSMAP_REDIS_INSTANCE_PORT
    value: "{{ .Values.global.cacheClusterPort }}"
  - name: LOCKSMAP_REDIS_INSTANCE_KEY
    value: "{{ .Values.global.cacheClusterKey }}"
  - name: DES_REDIS_INSTANCE_ADDRESS
    value: "{{ .Values.global.cacheClusterEndpoint }}"
  - name: DES_REDIS_INSTANCE_PORT
    value: "{{ .Values.global.cacheClusterPort }}"
  - name: DES_REDIS_INSTANCE_KEY
    value: "{{ .Values.global.cacheClusterKey }}"
  - name: ENTITLEMENTS_BASE_URL
    value: http://os-entitlements.osdu-services:8080
  - name: PARTITION_BASE_URL
    value: http://os-partition.osdu-services:8080
  - name: STORAGE_BASE_URL
    value: http://os-storage.osdu-services:8080
  - name: LEGAL_BASE_URL
    value: http://os-legal.osdu-services:8080
  - name: CLOUDPROVIDER
    value: aws
  - name: API_BASE_PATH
    value: "{{ .Values.service.apiPath }}"
  - name: SERVICE_ENV
    value: evd
  - name: JWKS_URL
    value: "{{ .Values.global.oauthJwksUri }}"
  - name: JWT_ENABLE_FEATURE
    value: "false"
  - name: FEATURE_FLAG_LOGGING
    value: "false"
  - name: FEATURE_FLAG_STACKDRIVER_EXPORTER
    value: "true"

# Resource Config
replicaCount: 1
resources:
  limits:
    memory: 900M
  requests:
    cpu: 500m
    memory: 900M
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
# Security Config
serviceAccountRole: arn:aws:iam::{{ .Values.global.accountID }}:role/osdu-{{ .Values.global.resourcePrefix }}-{{ .Values.global.region }}-{{ include "common.name" . }}
cors:
  maxAge: "60m"
  allowCredentials: true
  allowMethods:
    - POST
    - GET
    - PATCH
    - DELETE
  allowHeaders:
    - Authorization
    - Data-Partition-Id
    - Correlation-Id
    - Content-Type
securityContext: {}
podSecurityContext: 
  fsGroup: 1337
  seccompProfile:
    type: RuntimeDefault