include:
  # pipeline logic
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: v0.17.2

  # global
  # scanners
  # fossa
  - local: "devops/osdu/scanners/fossa.yml"

  # cloud-providers
  # aws
  - local: "devops/osdu/cloud-providers/aws.yml"

  # gcp
  - local: "devops/osdu/cloud-providers/gcp.yml"

  # azure
  - local: "devops/osdu/cloud-providers/azure.yml"

  # ibm
  - local: "devops/osdu/cloud-providers/ibm.yml"

  # app
  # sdms
  - local: "app/sdms/.gitlab-ci.yml"

  # file metadata service
  - local: "app/filemetadata/.gitlab-ci.yml"
