variables:
  #seismic store service variables
  ENVIRONMENT: cloud
  ISGITLAB: "true"
  PORT: 80
  REPLICA: 1
  UTEST_RUNTIME_IMAGE: seistore-svc-runtime
  SDMS_MIN_REPLICAS: 1
  SDMS_MAX_REPLICAS: 5

  #aws variables
  AWS_SERVICE: seismic-store
  AWS_BUILD_SUBDIR: src/cloud/providers/aws/build-aws
  AWS_TEST_SUBDIR: tests
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: EKS
  AWS_EKS_DEPLOYMENT_NAME: os-seismic-store
  AWS_BUILDER_DOCKERFILE_PATH: src/cloud/providers/aws/build-aws/builder.Dockerfile
  AWS_RUNTIME_DOCKERFILE_PATH: src/cloud/providers/aws/build-aws/runtime.Dockerfile
  # skipping tests here. Using a local file to run tests
  AWS_SKIP_TESTS: "true"
  #azure variables
  AZURE_SERVICE: seismic-store-service
  #gcp variables
  GCP_APPLICATION_NAME: os-seismic-store-service
  GCP_DEPLOY_FILE: $OSDU_GCP_DEPLOY_FILE
  GCP_PROJECT: opendes-evt
  GCP_SERVICE: seismic-store-service
  GCP_VENDOR: gcp
  #ibm variables
  IBM_OPENSHIFT_PROJECT: og-cicd
  IBM_VENDOR: ibm

  OSDU_GCP_LOG_LEVEL: INFO
  OSDU_GCP_SERVICE: seismic-store
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: seismic-store
  OSDU_GCP_APPLICATION: seismic-store
  OSDU_GCP_ENTITLEMENT_BASE_URL_PATH: /entitlements/v2
  OSDU_GCP_DATA_PARTITION_REST_HEADER_KEY: data-partition-id
  OSDU_GCP_DES_SERVICE_HOST_COMPLIANCE: https://community.osdu-gcp.go3-nrg.projects.epam.com/api
  OSDU_GCP_DES_SERVICE_HOST_STORAGE: https://os-storage-attcrcktoa-uc.a.run.app/api
  OSDU_GCP_ENV_VARS: CLOUDPROVIDER=${OSDU_GCP_CLOUD_PROVIDER},DES_SERVICE_HOST_PARTITION=${OSDU_GCP_PARTITION_API},ENTITLEMENT_BASE_URL_PATH=${OSDU_GCP_ENTITLEMENT_BASE_URL_PATH},DATA_PARTITION_REST_HEADER_KEY=${OSDU_GCP_DATA_PARTITION_REST_HEADER_KEY},DES_SERVICE_HOST_STORAGE=${OSDU_GCP_DES_SERVICE_HOST_STORAGE},DES_SERVICE_HOST_COMPLIANCE=${OSDU_GCP_DES_SERVICE_HOST_COMPLIANCE},SEISTORE_DES_TARGET_AUDIENCE=${GOOGLE_AUDIENCE},SERVICE_CLOUD_PROJECT=${OSDU_GCP_PROJECT},APP_ENVIRONMENT_IDENTIFIER=${TENANT},IMP_SERVICE_ACCOUNT_SIGNER=${OSDU_GCP_IMP_SERVICE_ACCOUNT_SIGNER},DES_SERVICE_HOST_ENTITLEMENT=${OSDU_GCP_ENTITLEMENTS_V2_BASE_URL},SEISTORE_DES_APPKEY=${OSDU_GCP_SEISTORE_DES_APPKEY},DES_REDIS_INSTANCE_ADDRESS=${OSDU_GCP_DES_REDIS_INSTANCE_ADDRESS},DES_REDIS_INSTANCE_PORT=${OSDU_GCP_DES_REDIS_INSTANCE_PORT},LOCKSMAP_REDIS_INSTANCE_ADDRESS=${OSDU_GCP_LOCKSMAP_REDIS_INSTANCE_ADDRESS}  --vpc-connector=$OSDU_GCP_VPC_CONNECTOR

include:
  # pipeline logic
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: release/0.11

  # build
  - local: "devops/osdu/build/seismic-store-service.yml"

  # scan
  # fossa
  - local: "devops/osdu/scanners/fossa-node.yml"
  
  # lint
  - local: "/devops/osdu/scanners/lint-node.yml"
  
  # scan for secrets
  - local: "/devops/osdu/scanners/scan-for-secrets-node.yml"

  # containerize
  - project: "osdu/platform/ci-cd-pipelines"
    file: "containerize/seismic-store-service.yml"
    ref: release/0.11

  # aws
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: release/0.11

  - local: "/devops/aws/awstest.yml"

  # deploy
  #azure
  - local: "/devops/osdu/cloud-providers/azure-seismic-store-service.yml"

    #ibm
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm-seismic-store-service.yml"
    ref: release/0.11
    #gcp
  - project: "osdu/platform/ci-cd-pipelines"
    ref: release/0.11
    file: "cloud-providers/osdu-gcp-cloudrun.yml"

osdu-gcp-test:
  script:
    - echo "Tests not implemented"
  extends:
    - .osdu-gcp-variables
  only:
    variables:
      - $OSDU_GCP == 'true' && $OSDU_GCP_INT_TEST_TYPE != 'python'

osdu-gcp-test-python:
  script:
    - echo "Tests not implemented"
  only:
    variables:
      - $OSDU_GCP == 'true' && $OSDU_GCP_INT_TEST_TYPE == 'python'

osdu-gcp-containerize-gitlab:
  stage: containerize
  needs: ["compile-and-unit-test"]
  tags: ["osdu-medium"]
  extends: .osdu-gcp-variables
  image: docker:19.03
  cache: {}
  allow_failure: true
  script:
    - export EXTRA_DOCKER_TAG=""; if [ "$CI_COMMIT_TAG" != "" ] ; then EXTRA_DOCKER_TAG="-t $CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_TAG" ; elif [ "$CI_COMMIT_REF_NAME" = "master" ] ; then EXTRA_DOCKER_TAG="-t $CI_REGISTRY_IMAGE/osdu-gcp:latest" ; fi
    - docker build -t $CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA $EXTRA_DOCKER_TAG --file docker/runtime.Dockerfile .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/osdu-gcp
  only:
    variables:
      - $OSDU_GCP == 'true'
