include:
  # pipeline logic
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: release/0.12

  # global
  # gcp
  - local: "devops/osdu/cloud-providers/gcp.yml"

  # app
  # sdms
  - local: "app/sdms/.gitlab-ci.yml"

  # file metadata service
  - local: "app/filemetadata/.gitlab-ci.yml"
