variables:
  #seismic store service variables
  SDMS_V4_SERVICE_NAME: seismic-ddms-v4

sdms_v4_azure_containerize:
  extends: .azure_containerize
  variables:
    SHA_IMAGE: ${SDMS_V4_SERVICE_NAME}:${CI_COMMIT_SHA}
    LATEST_IMAGE: ${SDMS_V4_SERVICE_NAME}:latest
    RELEASE_IMAGE: release-${CI_COMMIT_TAG}:${SDMS_V4_SERVICE_NAME}-${CI_COMMIT_TAG}
  script:
    - cd app/$SDMS_V4_SERVICE
    # Runtime image
    - docker build -t $SDMS_V4_UTEST_RUNTIME_IMAGE --file docker/runtime.Dockerfile .
    # Gitlab Container Registry
    - cd ../..
    # Runtime image
    - docker tag $SDMS_V4_UTEST_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker push ${CI_REGISTRY_IMAGE}/$SHA_IMAGE
    - docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE $CI_REGISTRY_IMAGE/$LATEST_IMAGE
    - docker push ${CI_REGISTRY_IMAGE}/$LATEST_IMAGE
    - docker tag ${CI_REGISTRY_IMAGE}/$LATEST_IMAGE $CI_REGISTRY_IMAGE/${SDMS_V4_PROJECT_NAME}azure:${CI_COMMIT_SHA}
    - docker push $CI_REGISTRY_IMAGE/${SDMS_V4_PROJECT_NAME}azure:${CI_COMMIT_SHA}
    # Azure Container Registry
    # Runtime image
    - az acr login -n $AZURE_REGISTRY
    - docker tag $SDMS_V4_UTEST_RUNTIME_IMAGE ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE
    - docker push ${AZURE_REGISTRY}.azurecr.io/$SHA_IMAGE
    - docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE
    - docker push ${AZURE_REGISTRY}.azurecr.io/$LATEST_IMAGE
    - |
      if [ ! -z "$CI_COMMIT_TAG" ]; then
        docker tag $CI_REGISTRY_IMAGE/$SHA_IMAGE ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
        docker push ${AZURE_REGISTRY}.azurecr.io/$RELEASE_IMAGE
      fi
  only:
    changes:
      - devops/**/*
      - app/sdms-v4/**/*
    refs:
      - branches
      - merge_requests
      - tags

sdms_v4_azure_container_scanning:
  extends: .azure_container_scanning
  needs:
    - sdms_v4_azure_containerize
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY_IMAGE}/${SDMS_V4_PROJECT_NAME}azure:${CI_COMMIT_SHA}
  rules:
    - if: $AZURE == '1' && $ENFORCE_CONTAINER_SCANNING == 'true'
      allow_failure: false
      changes:
        - devops/**/*
        - app/sdms-v4/**/*
    - if: $AZURE == '1'
      changes:
        - devops/**/*
        - app/sdms-v4/**/*