apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
  #common
  CLOUDPROVIDER: "{{ .Values.data.cloudProvider }}"
  APP_ENVIRONMENT_IDENTIFIER: "{{ .Values.data.appEnvironmentIdentifier }}"
  PORT: "{{ .Values.data.serverPort }}"
  SDMS_PREFIX: "{{ .Values.data.contextPath }}"
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"

  #API
  AUTHORIZE_API: "http://{{ .Release.Name }}-ibm-entitlement-deploy:8080/api/entitlements/v2"
  PARTITION_API: "http://{{ .Release.Name }}-ibm-partition-deploy:8080/api/partition/v1"
  POLICY_API: "http://{{ .Release.Name }}-ibm-policy-deploy:8080/api/policy/v1"

  STORAGE_CONTEXT_PATH: "{{ .Values.data.storageContextPath }}"
  ENTITLEMENT_CONTEXT_PATH: "{{ .Values.data.entitlementContextPath }}"
  COMPLIANCE_CONTEXT_PATH: "{{ .Values.data.legalContextPath }}"

  DES_SERVICE_HOST_STORAGE: "http://{{ .Release.Name }}-ibm-storage-deploy:8080"
  DES_SERVICE_HOST_COMPLIANCE: "http://{{ .Release.Name }}-ibm-legal-deploy:8080"
  DES_SERVICE_HOST_ENTITLEMENT: "http://{{ .Release.Name }}-ibm-entitlement-deploy:8080"

  #DB
  ibm.db.user: "{{ .Values.data.dbUser }}"
  ibm.db.password: "{{ .Values.data.dbPassw }}"

  #KEYCLOAK
  KEYCLOAK_REALM: "{{ .Values.data.keycloakRealm }}"

  #tenant-validation
  partition.keycloak.client_id: "{{ .Values.data.pKCClientId }}"
  KEYCLOAK_CLIENTID: "{{ .Values.data.KCClientId }}"
  partition.keycloak.client_secert: "{{ .Values.data.pKCClientSecret }}"
  KEYCLOAK_CLIENTSECRET: "{{ .Values.data.KCClientSecret }}"
  partition.keycloak.grant_type: "{{ .Values.data.pKCGrantType }}"
  KEYCLOAK_GRANTTYPE: "{{ .Values.data.KCGrantType }}"
  partition.keycloak.password: "{{ .Values.data.pKCPassword }}"
  KEYCLOAK_PASSWORD: "{{ .Values.data.KCPassword }}"
  partition.keycloak.realm: "{{ .Values.data.pKCRealm }}"
  partition.keycloak.url: "{{ .Values.data.pKCEndPointHost }}"
  partition.keycloak.user: "{{ .Values.data.pKCUser }}"
  KEYCLOAK_USERNAME: "{{ .Values.data.KCUser }}"
  tenantCache.exp.time.in.second: "{{ .Values.data.tenantCacheExpiryInSec }}"
  KEYCLOAK_URL_TOKEN: "{{ .Values.data.KCURLToken }}"
  KEYCLOAK_BASE_URL: "{{ .Values.data.KCBaseURL }}"


  # SEISMIC SPECIFICS
  REDIS_INSTANCE_PORT: "{{ .Values.data.redisPort }}"
  LOCKSMAP_REDIS_INSTANCE_ADDRESS: "{{ .Values.data.redisHost }}"
  IMP_SERVICE_ACCOUNT_SIGNER: "{{ .Values.data.impServiceAccountSigner }}"
  DES_REDIS_INSTANCE_KEY: "{{ .Values.data.redisInstanceKey }}"
  LOCKSMAP_REDIS_INSTANCE_KEY: "{{ .Values.data.redisInstanceKey }}"
  CACHE_TLS_DISABLE: "{{ .Values.data.cacheTLSDisable }}"
  
  COS_SUBUSER_SECRET_ACCESS_KEY: "{{ .Values.data.cosSubuserSecret }}" 
  COS_S3_FORCEPATHSTYLE: "{{ .Values.data.cosForcePathStyle }}"
  DOC_DB_QUERY_RESULT_LIMIT: "{{ .Values.data.docdbQueryLimit }}"
  COS_SUBUSER_ACCESS_KEY_ID: "{{ .Values.data.cosSubuserKeyID }}" 
  DOC_DB_QUERY_SELECT_FIELDS: "{{ .Values.data.docdbQueryFields }}"
  COS_ENDPOINT: "http://{{ .Release.Name }}-minio:9000"
  DB_URL: "{{ .Values.data.dbURL }}"
  COS_TEMP_CRED_EXPITY: "{{ .Values.data.cosTempCred }}"
  COS_SIGNATUREVERSION: "{{ .Values.data.cosSigVersion }}"
  DOC_DB_COLLECTION: "{{ .Values.data.docdbCollection }}"
  COS_SECRET_ACCESS_KEY: "{{ .Values.data.cosSecret }}"
  DOC_DB_QUERY_RESULT_LIMIT_VALUE: "{{ .Values.data.docdbQueryLimitValue }}"
  COS_ACCESS_KEY_ID: "{{ .Values.data.cosAccessKey }}" 