apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
  #common
  CLOUDPROVIDER: "{{ .Values.data.cloudProvider }}"
  APP_ENVIRONMENT_IDENTIFIER: "{{ .Values.data.appEnvironmentIdentifier }}"
  PORT: "{{ .Values.data.serverPort }}"
  SDMS_PREFIX: "{{ .Values.data.contextPath }}"
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"

  #API
  AUTHORIZE_API: "{{ tpl (.Values.data.services.authorize | default .Values.data.services.authorize) . }}"
  PARTITION_API: "{{ tpl (.Values.data.services.partition | default .Values.data.services.partition) . }}"
  POLICY_API: "{{ tpl (.Values.data.services.policy | default .Values.data.services.policy) . }}"

  STORAGE_CONTEXT_PATH: "{{ tpl (.Values.data.services.storagePath | default .Values.data.services.storagePath) . }}"
  ENTITLEMENT_CONTEXT_PATH: "{{ tpl (.Values.data.services.entitlementPath | default .Values.data.services.entitlementPath) . }}"
  COMPLIANCE_CONTEXT_PATH: "{{ tpl (.Values.data.services.legalPath | default .Values.data.services.legalPath) . }}"

  DES_SERVICE_HOST_STORAGE: "{{ tpl (.Values.data.services.storage | default .Values.data.services.storage) . }}"
  DES_SERVICE_HOST_COMPLIANCE: "{{ tpl (.Values.data.services.legal | default .Values.data.services.legal) . }}"
  DES_SERVICE_HOST_ENTITLEMENT: "{{ tpl (.Values.data.services.entitlement | default .Values.data.services.entitlement) . }}"

  #DB
  ibm.db.user: "{{ .Values.data.dbUser }}"
  ibm.db.password: "{{ .Values.data.dbPassw }}"

  tenantCache.exp.time.in.second: "{{ .Values.data.tenantCacheExpiryInSec }}"

  # SEISMIC SPECIFICS
  REDIS_INSTANCE_PORT: "{{ .Values.data.redisPort }}"
  LOCKSMAP_REDIS_INSTANCE_ADDRESS: "{{ .Values.data.redisHost }}"
  IMP_SERVICE_ACCOUNT_SIGNER: "{{ .Values.data.impServiceAccountSigner }}"
  DES_REDIS_INSTANCE_KEY: "{{ .Values.data.redisInstanceKey }}"
  LOCKSMAP_REDIS_INSTANCE_KEY: "{{ .Values.data.redisInstanceKey }}"
  CACHE_TLS_DISABLE: "{{ .Values.data.cacheTLSDisable }}"
  
  COS_SUBUSER_SECRET_ACCESS_KEY: "{{ .Values.data.cosSubuserSecret }}" 
  COS_S3_FORCEPATHSTYLE: "{{ .Values.data.cosForcePathStyle }}"
  DOC_DB_QUERY_RESULT_LIMIT: "{{ .Values.data.docdbQueryLimit }}"
  COS_SUBUSER_ACCESS_KEY_ID: "{{ .Values.data.cosSubuserKeyID }}" 
  DOC_DB_QUERY_SELECT_FIELDS: "{{ .Values.data.docdbQueryFields }}"
  COS_ENDPOINT: "{{ tpl (.Values.data.cosEndpoint | default .Values.data.cosEndpoint) . }}"
  DB_URL: "{{ .Values.data.dbURL }}"
  COS_TEMP_CRED_EXPIRY: "{{ .Values.data.cosTempCred }}"
  COS_SIGNATUREVERSION: "{{ .Values.data.cosSigVersion }}"
  DOC_DB_COLLECTION: "{{ .Values.data.docdbCollection }}"
  COS_SECRET_ACCESS_KEY: "{{ .Values.data.cosSecret }}"
  DOC_DB_QUERY_RESULT_LIMIT_VALUE: "{{ .Values.data.docdbQueryLimitValue }}"
  COS_ACCESS_KEY_ID: "{{ .Values.data.cosAccessKey }}" 