fossa-analyze:
  needs: ['sdms_compile-and-unit-test']
  image: $CI_REGISTRY/divido/fossa-with-cache:v0.8
  stage: scan
  tags: ['osdu-medium']
  variables:
    FOSSA_OUTPUT_DIR: fossa-output
    ALLOW_FOSSA_CACHE: 'false'
  before_script:
    - cd app/$SDMS_SERVICE
  script:
    # fossa-check-for-licensing-issues needs a CI_COMMIT_BRANCH defined to know how to parse the FOSSA API results
    # When building tags, this isn't defined by GitLab. In that case, we use the tag name instead. If that's not defined
    # then things will fail and we'll have to make this smarter
    - test -z "$CI_COMMIT_BRANCH" && export CI_COMMIT_BRANCH="$CI_COMMIT_TAG"
    - npm ci --production
    - fossa-with-cache --merge-with NOTICE
    - cd ../..
    - mv app/$SDMS_SERVICE/fossa-output .
  artifacts:
    paths:
      - fossa-output
    when: always
    expire_in: 2 days
  rules:
    - if: $FOSSA_API_KEY