sdms_fossa-analyze:
  extends: .fossa-analyze-node
  needs: ['sdms_compile-and-unit-test']
  variables:
    VAR_PROJECT_TITLE: $SDMS_PROJECT_TITLE
    FOSSA_OUTPUT_DIR: app/$SDMS_SERVICE/fossa-output
  before_script:
    - cd app/$SDMS_SERVICE/
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*

sdms_fossa-check-notice:
  extends: .fossa-check-notice
  needs: ['sdms_fossa-analyze']
  before_script:
    - cd app/$SDMS_SERVICE
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
  artifacts:
    when: on_failure
    paths:
      - app/$SDMS_SERVICE/public

sdms_fossa-report:
  extends: .fossa-report
  needs: ['sdms_fossa-analyze']
  variables:
    FOSSA_REPORT_URL: https://app.fossa.com/api/revisions/custom%2B12773%2F${SDMS_PROJECT_NAME}%24${CI_COMMIT_SHA}/attribution?access=${FOSSA_ACCESS}&includeProjectLicense=true&includeLicenseScan=true&includeDirectDependencies=true&includeDeepDependencies=true&includeLicenseHeaders=&includeLicenseList=true&format=HTML
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*