sdms_lint:
  image: node
  tags: ["osdu-small"]
  stage: scan
  needs: ['sdms_compile-and-unit-test']
  script:
    - cd app/$SERVICE
    - npm install -g typescript
    - npm install -g  tslint
    - npm run lint
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - main
      - merge_requests