sdms_scan-for-secrets:
  image: community.opengroup.org:5555/osdu/platform/domain-data-mgmt-services/seismic/seismic-dms-suite/seismic-store-service/seismic-store-service-detect-secrets:latest
  tags: ["osdu-small"]
  stage: scan
  needs:
    - job: sdms_compile-and-unit-test
      artifacts: false
  script:
    - cd app/$SDMS_SERVICE
    - detect-secrets-hook --exclude-files npm-shrinkwrap.json --exclude-files package.json --exclude-files devops/osdu/scanners/scan-for-secrets-node.yml --baseline devops/docker/detect_secrets/.secrets.baseline $(git ls-files)
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - merge_requests
