parameters:
  serviceName: ''
  providerName: ''
  chartPath: ''
  manifestRepo: ''
  hldRegPath: ''
  environment: ''
  fluxEnabled: false
  installRequirements: false
steps:
  - template: aks-deployment-steps.yml
    parameters:
      serviceName: ${{ parameters.serviceName }}
      providerName: ${{ parameters.providerName }}
      environment: ${{ parameters.environment }}
      chartPath: ${{ parameters.chartPath }}
      hldRegPath: ${{ parameters.hldRegPath }}
      skipDeploy: ${{ parameters.skipDeploy }}
      manifestRepo: ${{ parameters.manifestRepo }}
      fluxEnabled: ${{ parameters.fluxEnabled }}
      installRequirements: ${{ parameters.installRequirements }}