steps:
    - task: Bash@3
      displayName: "Generate tokens"
      env:
        e2esauthurl: $(e2esauthurl)
        sauthSvcApiKey: $(sauthSvcApiKey)
        e2eProjectId: $(e2eProjectId)
        e2eServiceId: $(e2eServiceId)
        e2esauthTesterSvcAccountSecret: $(sauthTesterSvcAccountSecret)
        e2eTargetProjId: $(e2eTargetProjectId)
        e2eTargetServiceId: $(e2eTargetServiceId)
        e2eServiceId1: $(e2eServiceId1)
        e2esauthTesterSvcAccountSecret1: $(sauthTesterSvcAccountSecret1)
        e2eServiceIdSa: $(e2eServiceIdSa)
        e2eServiceIdSe: $(e2eServiceIdSe)
        e2eServiceIdSv: $(e2eServiceIdSv)
        e2estoken_ta: $(e2estoken_ta)
        e2estoken_sa: $(e2estoken_sa)
        e2estoken_se: $(e2estoken_se)
        e2estoken_sv: $(e2estoken_sv)
        e2esauthTesterSvcAccountSecretSa: $(e2esauthTesterSvcAccountSecretSa)
        e2esauthTesterSvcAccountSecretSe: $(e2esauthTesterSvcAccountSecretSe)
        e2esauthTesterSvcAccountSecretSv: $(e2esauthTesterSvcAccountSecretSv)
        
      inputs:
        targetType: "inline"
        script: |
          #!/usr/bin/env bash

          svctoken=$(curl -X POST ${e2esauthurl} \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: '"${sauthSvcApiKey}"'' \
          -d '{
                "projectid": "'"${e2eProjectId}"'", 
                "serviceid": "'"${e2eServiceId}"'",
                "secret": "'"${e2esauthTesterSvcAccountSecret}"'",
                "targetserviceid": "'"${e2eTargetServiceId}"'",
                "targetprojid": "'"${e2eTargetProjId}"'"
              }' | jq ."svctoken" -r )
          echo "##vso[task.setvariable variable=e2eIdToken]$svctoken"
          echo "##vso[task.setvariable variable=e2estoken_ta]$svctoken"
          
          e2eIdToken1=$(curl -X POST ${e2esauthurl} \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: '"${sauthSvcApiKey}"'' \
          -d '{
            "projectid": "'"${e2eProjectId}"'", 
            "serviceid": "'"${e2eServiceId1}"'",
            "secret": "'"${e2esauthTesterSvcAccountSecret1}"'",
            "targetserviceid": "'"${e2eTargetServiceId}"'",
            "targetprojid": "'"${e2eTargetProjId}"'"
          }' | jq ."svctoken" -r )
          echo "##vso[task.setvariable variable=e2eIdToken1]$e2eIdToken1"

          e2eIdTokenSa=$(curl -X POST ${e2esauthurl} \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: '"${sauthSvcApiKey}"'' \
          -d '{
            "projectid": "'"${e2eProjectId}"'", 
            "serviceid": "'"${e2eServiceIdSa}"'",
            "secret": "'"${e2esauthTesterSvcAccountSecretSa}"'",
            "targetserviceid": "'"${e2eTargetServiceId}"'",
            "targetprojid": "'"${e2eTargetProjId}"'"
          }' | jq ."svctoken" -r )
          echo "##vso[task.setvariable variable=e2estoken_sa]$e2eIdTokenSa"
          
          e2eIdTokenSe=$(curl -X POST ${e2esauthurl} \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: '"${sauthSvcApiKey}"'' \
          -d '{
            "projectid": "'"${e2eProjectId}"'", 
            "serviceid": "'"${e2eServiceIdSe}"'",
            "secret": "'"${e2esauthTesterSvcAccountSecretSe}"'",
            "targetserviceid": "'"${e2eTargetServiceId}"'",
            "targetprojid": "'"${e2eTargetProjId}"'"
          }' | jq ."svctoken" -r )
          echo "##vso[task.setvariable variable=e2estoken_se]$e2eIdTokenSe"

          e2eIdTokenSv=$(curl -X POST ${e2esauthurl} \
          -H 'Cache-Control: no-cache' \
          -H 'Content-Type: application/json' \
          -H 'x-api-key: '"${sauthSvcApiKey}"'' \
          -d '{
            "projectid": "'"${e2eProjectId}"'", 
            "serviceid": "'"${e2eServiceIdSv}"'",
            "secret": "'"${e2esauthTesterSvcAccountSecretSv}"'",
            "targetserviceid": "'"${e2eTargetServiceId}"'",
            "targetprojid": "'"${e2eTargetProjId}"'"
          }' | jq ."svctoken" -r )
          echo "##vso[task.setvariable variable=e2estoken_sv]$e2eIdTokenSv"