steps:
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish Code Coverage'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
      reportDirectory: '$(Build.SourcesDirectory)/coverage'