parameters:
  providerName: ""
steps:
  - task: Bash@3
    displayName: "Build Runtime Image"
    inputs:
      targetType: "inline"
      script: |
        cd $(Build.Repository.LocalPath)
        sudo docker build -t $(runtime_image) --file Dockerfile .
        mkdir ${{ parameters.providerName }}
        docker save -o ${{ parameters.providerName }}/$(runtime_image).tar $(runtime_image)
