parameters:
  createChangeManagement: false
  environment: ""
steps:
  - task: ManualValidation@0
    condition: ${{ parameters.createChangeManagement }}
    timeoutInMinutes: 1440 # task times out in 1 day
    inputs:
      instructions: 'Please validate Change Management ticket was created and approved so ${{ parameters.environment }} deployment can be triggered.'
      onTimeout: 'reject'