parameters:
  serviceName: ""
  providerName: ""
  environment: ""
  secureFile: ""
  installRequirements: false

steps:
  - task: AzureCLI@1
    name: PushRuntimeImage
    displayName: 'Push Runtime Image'
    condition: and(succeeded(), eq('${{ parameters.providerName }}', 'Azure'))
    env:
      IMAGE: $(CONTAINER_REGISTRY_NAME).azurecr.io/${{ parameters.imageRepoName }}:$(Build.BuildId)-${{ parameters.environment }}
    inputs:
      azureSubscription: '$(SERVICE_CONNECTION_NAME)'
      addSpnToEnvironment: true
      scriptLocation: inlineScript
      inlineScript: |
       !/usr/bin/env bash
        set -euo pipefail

        echo "Logging in to the ACR Registry"
        echo "------------------------------------"
        az acr login -n $(CONTAINER_REGISTRY_NAME)

        echo "------------------------------------"
        docker load --input ${{ parameters.providerName }}_$(runtime_image)/$(runtime_image).tar
        docker tag $(runtime_image) $(CONTAINER_REGISTRY_NAME).azurecr.io/$(runtime_image):$(Build.SourceBranchName)-$(Build.BuildNumber)
        
        docker push $(CONTAINER_REGISTRY_NAME).azurecr.io/$(runtime_image):$(Build.SourceBranchName)-$(Build.BuildNumber)