global:
  domain: ""
  onPremEnabled: false

data:
  # Configmap
  logLevel: "ERROR"
  cloudProvider: "google"
  port: "5000"
  desServiceHost: "https://des"
  partitionHost: "http://partition"
  entitlementBaseUrlPath: "/entitlements/v2"
  dataPartitionRestHeaderKey: "data-partition-id"
  storageHost: "http://storage"
  legalHost: "http://legal"
  appEnvironmentIdentifier: "dev"
  entitlementsHost: "http://entitlements"
  redisDdmsHost: "redis-ddms-master.redis.svc.cluster.local"
  redisPort: "6379"
  redisSdmsHost: ""
  redisSdmsPort: "6379"
  redisSdmsTlsDisabled: true
  urlPrefix: "/api/seismic-store/v3"
  impServiceAccountSigner: "NA"
  seistoreDesAppkey: "NA"
  serviceCloudProject: ""
  googleAudiences: ""
  apiBasePath: "/api/v3"
  serviceEnv: "dev"
  # Deployment
  requestsCpu: "10m"
  requestsMemory: "200Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "seismic-store"
  imagePullPolicy: "IfNotPresent"
  redisImage: "docker.io/library/redis:7"
  image: ""

conf:
  configmap: "seismic-store-config"
  appName: "seismic-store"
  urlPrefix: "/api/seismic-store/v3"
  # onprem configuration
  database: "seismic-store-db-secret"
  keycloak: "seismic-store-keycloak-secret"
  minio: "seismic-store-minio-secret"
  sdmsRedisSecretName: "seismic-store-redis-secret" # pragma: allowlist secret

istio:
  proxyCPU: "10m"
  proxyCPULimit: "500m"
  proxyMemory: "100Mi"
  proxyMemoryLimit: "512Mi"
