apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Values.image.tag }}
    release: {{ .Chart.Name }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}