apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Values.image.tag }}
    release: {{ .Release.Name }}
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
  selector:
    app: {{ .Release.Name }}
