parameters:
  serviceName: ''
  environment: ""
  provider: ''
  type: ''
stages:

  - stage: 'Change_Management_${{ parameters.type }}_${{ parameters.provider }}_${{ parameters.environment }}'
    variables:
      - group: '${{ parameters.provider }} Target Env - ${{ parameters.serviceName }} - ${{ parameters.environment }}'
      - group: '${{ parameters.provider }} Target Env Secrets - ${{ parameters.serviceName }} - ${{ parameters.environment }}'
      - group: '${{ parameters.provider }} Service Release - ${{ parameters.serviceName }}'
    jobs:
      - job: Create_Change_Management
        pool:
          name: $(AGENT_POOL)
          vmImage: $(AGENT_IMAGE)
        workspace:
          clean: all
        steps:
          - template: task/create-change-management-steps.yml
            parameters:
              createChangeManagement: 'true'
              providerName: ${{ parameters.provider }}
              environment: ${{ parameters.environment }}
      - job: Validate_Change_Management
        pool: server
        dependsOn: Create_Change_Management
        timeoutInMinutes: 4320
        workspace:
          clean: all
        steps:
          - template: task/validate-change-management-steps.yml
            parameters:
              createChangeManagement: 'true'
              environment: ${{ parameters.environment }}