parameters:
  serviceName: ''
  providers: []
  manifestRepo: ''
  environmentPrefix: ""
  fluxEnabled: true
  installRequirements: false
  isGitlab: false
  secureFile: ""
  osdu_commit: ""
stages:

- ${{ each provider in parameters.providers }}:
  - ${{ each environment in provider.environments }}:
    - stage: 'Deploy_${{ provider.name }}_${{ environment.name }}'
      variables:
      - group: '${{ provider.name }} Target Env - ${{ environment.name }}'
      - group: '${{ provider.name }} Target Env Secrets - ${{ environment.name }}'
      - group: '${{ provider.name }} Service Release - ${{ parameters.serviceName }}'
      jobs:
      - deployment: Deploy_Image
        pool:
          name: $(AGENT_POOL)
          vmImage: $(AGENT_IMAGE)
        environment: ${{ parameters.environmentPrefix }}${{ environment.name }}
        strategy:
          runOnce:
            deploy:
              steps:
              - download: none
              - template: task/deployment-image-steps.yml
                parameters:
                  serviceName: ${{ parameters.serviceName }}
                  providerName: ${{ provider.name }}
                  environment: ${{ environment.name }}
                  secureFile: ${{ environment.secureFile }}
                  installRequirements: ${{ parameters.installRequirements }}
      - deployment: Deploy_To_Cluster
        dependsOn: Deploy_Image
        timeoutInMinutes: 720
        pool:
          name: $(AGENT_POOL)
          vmImage: $(AGENT_IMAGE)
        workspace:
          clean: all
        environment: ${{ parameters.environmentPrefix }}${{ environment.name }}
        strategy:
          runOnce:
            deploy:
              steps:
              - download: none
              - template: task/deployment-helm-steps.yml
                parameters:
                  serviceName: ${{ parameters.serviceName }}
                  providerName: ${{ provider.name }}
                  chartPath: $(chartPath)
                  environment: ${{ environment.name }}
                  fluxEnabled: ${{ environment.fluxEnabled }}
                  secureFile: ${{ environment.secureFile }}
                  installRequirements: ${{ parameters.installRequirements }}
                  manifestRepo: ${{ parameters.manifestRepo }}