include:
  # global
  - local: "app/sdms/devops/osdu/global/gitlab.yml"

  # build
  - local: "app/sdms/devops/osdu/build/seismic-store-service.yml"

  # scan
  # fossa
  - local: "app/sdms/devops/osdu/scanners/fossa.yml"

  # lint
  - local: "app/sdms/devops/osdu/scanners/lint-node.yml"

  # scan for secrets
  - local: "app/sdms/devops/osdu/scanners/scan-for-secrets-node.yml"

  # containerize
  # osdu

  # this job doesn't work for a long time
  #  - local: "app/sdms/devops/osdu/containerize/osdu.yml"

  # deploy
  # azure
  - local: "app/sdms/devops/osdu/cloud-providers/azure.yml"

  # aws
  # - local: "app/sdms/devops/osdu/cloud-providers/aws.yml"

<<<<<<< HEAD
  # # gcp
  # - local: "app/sdms/devops/osdu/cloud-providers/gcp.yml"
=======
  # Google Cloud
  - local: "app/sdms/devops/osdu/cloud-providers/gc.yml"
>>>>>>> aba5a6666dc52250da1681564d0286c85957d34e

  # # ibm
  # - local: "app/sdms/devops/osdu/cloud-providers/ibm.yml"
