data:
  log_level: "INFO"
  cloudprovider: "google"
  des_service_host_partition: "http://partition/api/partition/v1/"
  entitlement_base_url_path: "/entitlements/v2"
  data_partition_rest_header_key: ""
  des_service_host_storage: "http://storage/api/storage/v2"
  des_service_host_compliance: "http://legal/api/legal/v1"
  seistore_des_target_audience: ""
  service_cloud_project: ""
  app_environment_identifier: "osdu"
  imp_service_account_signer: ""
  des_service_host_entitlement: "http://entitlements/api"
  seistore_des_appkey: ""
  des_redis_instance_address: ""
  des_redis_instance_port: "6379"
  locksmap_redis_instance_address: ""
  locksmap_redis_instance_port: "6379"
conf:
  configmap: "seismic-store-config"
  app_name: "seismic-store"
