data:
  # common configuration
  logLevel: "ERROR"
  cloudProvider: "google"
  port: "5000"
  desServiceHost: "https://des"
  partitionHost: "http://partition"
  entitlementBaseUrlPath: "/entitlements/v2"
  dataPartitionRestHeaderKey: "data-partition-id"
  storageHost: "http://storage"
  legalHost: "http://legal"
  appEnvironmentIdentifier: "dev"
  entitlementsHost: "http://entitlements"
  redisDdmsHost: "redis-ddms-master.redis.svc.cluster.local"
  redisPort: "6379"
  urlPrefix: "/api/seismic-store/v3"
  # gcp configuration
  impServiceAccountSigner: "NA"
  seistoreDesAppkey: "NA"
  serviceCloudProject: ""
  googleAudiences: ""
  # onprem configuration
  apiBasePath: "/api/v3"
  serviceEnv: "dev"
conf:
  appName: "seismic-store"
  configmap: "seismic-store-config"
  onPremEnabled: false
