#  Copyright © Microsoft Corporation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Annotation to support the key rotation for redis password in keyvaul
deployment:
  replicaCount: 2
  deploymentAnnotations:
    secret.reloader.stakater.com/reload: "{{.Release.Name }}-secret"

azure:
  keyvault:
    secrets:
    - key: k8.redis.password
      obj: redis-password

configuration:
  ###################
  # Seismic Service #
  ###################
# seismic sdms
  - service: seismic-ddms
    container:
      image: seismic-ddms
      tag: latest
      containerPort: 8080
    path: /seistore-svc/api/v3
  # FIXME: Prometheus instrumentation needs to be implememented for Seismic DDMS and Seismic File Metadata
  # podAnnotations:
    # prometheus.io/path: /seistore-svc/api/v3/metrics
    # prometheus.io/port: "80"
    # prometheus.io/scrape: "true"
#    autoscale:
#      minReplicas: 1
#      maxReplicas: 5
    probe:
      readiness:
        path: /seistore-svc/api/v3/svcstatus/readiness
      liveness:
        path: /seistore-svc/api/v3/svcstatus
    auth:
      disable:
        - "/seistore-svc/api/v3/swagger-ui.html*"
        - "/seistore-svc/api/v3/svcstatus"
        - "/seistore-svc/api/v3/svcstatus/readiness"
    config:
      DES_SERVICE_HOST: "https://{{ .Values.ingress.dns }}"
      REDIS_INSTANCE_PORT: "6380"
      APP_ENVIRONMENT_IDENTIFIER: "cloud"
      CLOUDPROVIDER: "azure"
      PORT: "8080"
      KEYVAULT_URL: "https://{{ .Values.azure.keyvault.name }}.vault.azure.net/"
      SIDECAR_URL: "https://localhost:7138"
      SIDECAR_ENABLE_INSERT: "false"
      SIDECAR_ENABLE_GET: "false"
      SIDECAR_ENABLE_DELETE: "false"
      SIDECAR_ENABLE_QUERY: "true"
    # Use only for secret rotation
    secrets:
      - name: AZ_REDIS_PASSWORD
        key: k8.redis.password
    request:
      cpu: 0.1
      memory: 1Gi
    limit:
      cpu: 1
      memory: 4Gi
# sidecar sdms
    sidecar:
      name: seismic-ddms-sidecar
      container:
        image: seismic-ddms-sidecar
        tag: latest
        containerPort: 7138
      config:
        ASPNETCORE_URLS: "https://+:7138;http://+:5160"
        ASPNETCORE_ENVIRONMENT: "Development"
        ASPNETCORE_Kestrel__Certificates__Default__Path: /app/aspnetapp.pfx
      request:
        cpu: 0.1
        memory: 1Gi
      limit:
        cpu: 1
        memory: 2Gi
