global:
  replicaCount: #{REPLICA_COUNT}#
  namespace: osdu
  podidentity: osdu-identity
  nodepool: services
  isAutoscalingEnabled: false
  minReplicaCount: #{SDMS_MIN_REPLICAS}#
  maxReplicaCount: #{SDMS_MAX_REPLICAS}#
 
 
configEnv:
  cloudProvider: #{PROVIDER_NAME}#
  keyvaultUrl: #{KEYVAULT_NAME}#
  desServiceHost: #{DNS_HOST}#
  redisInstanceAddress: #{REDIS_HOST}#
  redisInstancePort: #{REDIS_PORT}#
  appEnvironmentIdentifier: #{ENVIRONMENT_NAME}#
  port: #{PORT}#

image:
  repository: #{CONTAINER_REGISTRY_NAME}#
  branch: master
  tag: #{IMAGE_TAG}#
