global:
  replicaCount: #{REPLICA_COUNT}#
  namespace: osdu
  podidentity: osdu-identity
  nodepool: services
  isAutoscalingEnabled: false
  minReplicaCount: #{MIN_REPLICA_COUNT}#
  maxReplicaCount: #{MAX_REPLICA_COUNT}#
 
configEnv:
  cloudProvider: #{PROVIDER_NAME}#
  desServiceHost: #{DNS_HOST}#

image:
  repository: #{CONTAINER_REGISTRY_NAME}#
  branch: master
  tag: #{IMAGE_TAG}#