variables:
  GCP_SDMS_PREFIX: /api/seismic-store/v3

sdms-osdu-gcp-helm-charts:
  variables:
    SEISMIC_OSDU_GCP_HELM_PACKAGE_CHARTS: "app/sdms/devops/gcp/deploy app/sdms/devops/gcp/configmap"
    SEISMIC_OSDU_GCP_HELM_CONFIG_DIR: "app/sdms/devops/gcp/configmap"
    SEISMIC_OSDU_GCP_HELM_DEPLOYMENT_DIR: "app/sdms/devops/gcp/deploy" 
  extends: .osdu-gcp-helm-charts
  before_script:
    - sed -i 's|#{SDMS_PREFIX}#|'$GCP_SDMS_PREFIX'|' ${SEISMIC_OSDU_GCP_HELM_CONFIG_DIR}/values.yaml
    - sed -i 's|#{SDMS_PREFIX}#|'$GCP_SDMS_PREFIX'|' ${SEISMIC_OSDU_GCP_HELM_DEPLOYMENT_DIR}/values.yaml
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*

sdms-osdu-gcp-containerize-gitlab:
  variables:
    SEISMIC_OSDU_GCP_DOCKERFILE_NAME: "docker/runtime.Dockerfile"
    SEISMIC_OSDU_GCP_SERVICE: seismic-store    
  extends: .osdu-gcp-containerize-gitlab
  before_script:
    - cd app/$SDMS_SERVICE
    - sed -i 's|#{SDMS_PREFIX}#|'$GCP_SDMS_PREFIX'|' ./docs/api/openapi.osdu.yaml
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*

sdms-osdu-gcp-deploy-configmap:
  variables:
    SEISMIC_OSDU_GCP_HELM_CONFIG_SERVICE: seismic-store-configmap
    SEISMIC_OSDU_GCP_HELM_CONFIG_DIR: "app/sdms/devops/gcp/configmap"
    SEISMIC_OSDU_GCP_HELM_CONFIG_SERVICE_VARS: "--set data.domain=$DOMAIN"
  extends: .osdu-gcp-deploy-configmap
  before_script:
    - sed -i 's|#{SDMS_PREFIX}#|'$GCP_SDMS_PREFIX'|' ${SEISMIC_OSDU_GCP_HELM_CONFIG_DIR}/values.yaml
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*

sdms-osdu-gcp-deployment:
  variables:
    SEISMIC_OSDU_GCP_HELM_DEPLOYMENT_SERVICE: seismic-store-deploy
    SEISMIC_OSDU_GCP_HELM_DEPLOYMENT_DIR: "app/sdms/devops/gcp/deploy"
    SEISMIC_OSDU_GCP_SERVICE: seismic-store
    SEISMIC_OSDU_GCP_HELM_DEPLOYMENT_SERVICE_VARS: "--set data.image=$CI_REGISTRY_IMAGE/osdu-gcp-$SEISMIC_OSDU_GCP_SERVICE:$CI_COMMIT_SHORT_SHA"
  extends: .osdu-gcp-deployment
  needs: ["sdms-osdu-gcp-containerize-gitlab", "sdms-osdu-gcp-deploy-configmap"]
  before_script:
    - sed -i 's|#{SDMS_PREFIX}#|'$GCP_SDMS_PREFIX'|' ${SEISMIC_OSDU_GCP_HELM_DEPLOYMENT_DIR}/values.yaml
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
