variables:
  # Services
  SEISMIC_HOST: $IBM_SEISMIC_HOST

sdms_ibm-deploy:
  extends: .ibm-deploy
  needs: ['sdms_compile-and-unit-test']
  script:
    - cd app/$SDMS_SERVICE
    - echo "In IBM deploy"
    - oc project $IBM_OPENSHIFT_PROJECT
    - oc get bc/$SDMS_PROJECT_NAME 2> /dev/null || oc new-build --name $SDMS_PROJECT_NAME --binary --strategy source --image-stream openshift/ubi8-nodejs-14
    - oc start-build $SDMS_PROJECT_NAME --commit=$CI_COMMIT_SHA  --follow
    - oc get service $SDMS_PROJECT_NAME 2> /dev/null || oc new-app $SDMS_PROJECT_NAME
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - main
      - merge_requests
      - tags
      
sdms_ibm-deploy-devpri:
  extends: .ibm-deploy-devpri
  needs: ['sdms_compile-and-unit-test']
  script:
    - cd app/$SDMS_SERVICE
    - echo "In IBM deploy"
    - oc login --token=$IBM_PRIMARY_DEV_TOKEN --server=$IBM_PRIMARY_DEV_URL
    - oc project $IBM_OPENSHIFT_DEVPRI_PROJECT
    - oc get bc/$SDMS_PROJECT_NAME 2> /dev/null || oc new-build --name $SDMS_PROJECT_NAME --binary --strategy source --image-stream openshift/ubi8-nodejs-14
    - oc start-build $SDMS_PROJECT_NAME --from-dir=. --follow
    - oc get service $SDMS_PROJECT_NAME 2> /dev/null || oc new-app $SDMS_PROJECT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - devops/**/*
        - app/sdms/**/*
    
sdms_ibm-test-py:
  image: node
  stage: integration
  extends:
    - .ibm-test-py
  needs: ["sdms_ibm-deploy"]
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -y python
    - apt-get install -y python3-pip
    - pip install requests
    - svctoken=$(python3 ../../devops/scripts/ibm_jwt_client.py)
    - echo $svctoken > /dev/null
    - npm install -g newman
    - npm install -g husky
    - npm install -g node-pre-gyp
    - npm install
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - ./tests/e2e/run_e2e_tests.sh --seistore-svc-url="https://${SEISMIC_HOST}/api/v3" --seistore-svc-api-key="NA" --user-idtoken="$svctoken" --tenant="${IBM_SEISMIC_E2E_TENANT}" --admin-email="${IBM_SEISMIC_E2E_ADMIN_EMAIL}" --datapartition="${IBM_SEISMIC_E2E_DATA_PARTITION}" --legaltag01="${IBM_SEISMIC_E2E_LEGALTAG01}" --legaltag02="${IBM_SEISMIC_E2E_LEGALTAG02}" --newuser="${IBM_SEISMIC_E2E_NEWUSER}" --VCS-Provider="gitlab"  --subproject="${IBM_SEISMIC_E2E_SUBPROJECT}"
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - main
      - merge_requests
      - tags

sdms_ibm-preship-promote:
  extends: .ibm-preship-promote
  needs: ['sdms_ibm-test-py']
  script:
    - cd app/$SDMS_SERVICE
    - oc login --token=$IBM_PRESHIP_OPENSHIFT_TOKEN --server=$IBM_PRESHIP_OPENSHIFT_URL
    - oc project $IBM_OPENSHIFT_PRESHIP_PROJECT
    - oc start-build og-$SDMS_PROJECT_NAME-ibm
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - devops/**/*
        - app/sdms/**/*
        
sdms_ibm-preship-promote-release:
  extends: .ibm-preship-promote-release
  stage: publish
  needs: ['sdms_ibm-test-py']
  script:
    - cd app/$SDMS_SERVICE
    - oc login --token=$IBM_PRESHIP_OPENSHIFT_TOKEN --server=$IBM_PRESHIP_OPENSHIFT_URL
    - oc project $IBM_OPENSHIFT_PRESHIP_PROJECT
    - oc start-build og-$SDMS_PROJECT_NAME-monthly-ibm --commit=$CI_COMMIT_SHA --follow
  rules:
    - if: '$CI_COMMIT_BRANCH == $IBM_PRESHIP_RELEASE_BRANCH'
      changes:
        - devops/**/*
        - app/sdms/**/*