include:
  - local: "devops/osdu/cloud-providers/ibm.yml"

variables:
  #ibm variables
  IBM_OPENSHIFT_PROJECT: og-cicd
  IBM_VENDOR: ibm


sdms_ibm-deploy:
  extends: .ibm
  stage: deploy
  needs: ['sdms_compile-and-unit-test']
  script:
    - cd app/$SDMS_SERVICE
    - echo "In IBM deploy"
    - oc project $IBM_OPENSHIFT_PROJECT
    - oc get bc/$SDMS_PROJECT_NAME 2> /dev/null || oc new-build --name $SDMS_PROJECT_NAME --binary --strategy source --image-stream openshift/ubi8-nodejs-14
    - oc start-build $SDMS_PROJECT_NAME --from-dir=. --follow
    - oc get service $SDMS_PROJECT_NAME 2> /dev/null || oc new-app $SDMS_PROJECT_NAME
  only:
    variables:
      - $IBM == 'true'
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - main
      - merge_requests
      
sdms_ibm-deploy-devpri:
  extends: .ibm
  stage: deploy
  needs: ['sdms_compile-and-unit-test']
  script:
    - cd app/$SDMS_SERVICE
    - echo "In IBM deploy"
    - oc login --token=$IBM_PRIMARY_DEV_TOKEN --server=$IBM_PRIMARY_DEV_URL
    - oc project $IBM_OPENSHIFT_DEVPRI_PROJECT
    - oc get bc/$SDMS_PROJECT_NAME 2> /dev/null || oc new-build --name $SDMS_PROJECT_NAME --binary --strategy source --image-stream openshift/ubi8-nodejs-14
    - oc start-build $SDMS_PROJECT_NAME --from-dir=. --follow
    - oc get service $SDMS_PROJECT_NAME 2> /dev/null || oc new-app $SDMS_PROJECT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - devops/**/*
        - app/sdms/**/*
    
sdms_ibm-test:
  tags: ["osdu-medium"]
  image: node
  stage: integration
  extends:
    - .ibm_variables
  allow_failure: false
  needs: ["sdms_ibm-deploy"]
  script:
    - cd app/$SDMS_SERVICE
    - apt-get update
    - apt-get install -y python3
    - apt-get install -y python3-pip
    - pip3 install requests
    - svctoken=$(python3 devops/scripts/ibm_jwt_client.py)
    - echo $svctoken > /dev/null
    - npm install -g newman
    - chmod +x ./tests/e2e/run_e2e_tests.sh
    - ./tests/e2e/run_e2e_tests.sh --seistore-svc-url="https://${SEISMIC_HOST}/api/v3" --seistore-svc-api-key="NA" --user-idtoken="$svctoken" --tenant="${IBM_SEISMIC_E2E_TENANT}" --admin-email="${IBM_SEISMIC_E2E_ADMIN_EMAIL}" --datapartition="${IBM_SEISMIC_E2E_DATA_PARTITION}" --legaltag01="${IBM_SEISMIC_E2E_LEGALTAG01}" --legaltag02="${IBM_SEISMIC_E2E_LEGALTAG02}" --newuser="${IBM_SEISMIC_E2E_NEWUSER}" --VCS-Provider="gitlab"
  only:
    variables:
      - $IBM == 'true'
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - main
      - merge_requests

sdms_ibm-preship-promote:
  extends: .ibm
  stage: publish
  needs: ['sdms_ibm-test']
  script:
    - cd app/$SDMS_SERVICE
    - oc login --token=$IBM_PRESHIP_OPENSHIFT_TOKEN --server=$IBM_PRESHIP_OPENSHIFT_URL
    - oc project $IBM_OPENSHIFT_PRESHIP_PROJECT
    - oc start-build og-$SDMS_PROJECT_NAME-ibm
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - devops/**/*
        - app/sdms/**/*
