sdms_push_runtime_image:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  tags: ["osdu-medium"]
  needs: ['sdms_compile-and-unit-test']
  stage: containerize
  variables:
    SHA_IMAGE: ${SDMS_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}
    LATEST_IMAGE: ${SDMS_PROJECT_NAME}:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Gitlab Container Registry
    - export directoryToScan=$PWD
    - export currentDirectory=$PWD
    - chmod +x app/$SDMS_SERVICE/devops/scripts/detect_unused_packages.sh
    - app/$SDMS_SERVICE/devops/scripts/detect_unused_packages.sh
    - cd app/$SDMS_SERVICE
    - docker build -t $SDMS_UTEST_RUNTIME_IMAGE --file docker/runtime.Dockerfile  .
    - docker tag $SDMS_UTEST_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$SHA_IMAGE
    - docker tag $SDMS_UTEST_RUNTIME_IMAGE $CI_REGISTRY_IMAGE/$LATEST_IMAGE
    - docker push $CI_REGISTRY_IMAGE/$LATEST_IMAGE
  only:
    changes:
      - devops/**/*
      - app/sdms/**/*
    refs:
      - branches
      - merge_requests
      - tags
