apiVersion: v1
kind: ConfigMap
metadata:
  name: seismic-file-metadata-properties
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
data:
  CLOUDPROVIDER: {{ .Values.configEnv.cloudProvider }}
  SDMS_SERVICE_HOST: https://{{ .Values.configEnv.desServiceHost }}/seistore-svc/api/v3