apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  LOG_LEVEL: {{ .Values.data.logLevel  | quote }}
  CLOUDPROVIDER: {{ .Values.data.cloudProvider  | quote }}
  DES_SERVICE_HOST_PARTITION: {{ .Values.data.partitionHost  | quote }}
  ENTITLEMENT_BASE_URL_PATH: {{ .Values.data.entitlementBaseUrlPath  | quote }}
  DATA_PARTITION_REST_HEADER_KEY: {{ .Values.data.dataPartitionRestHeaderKey  | quote }}
  DES_SERVICE_HOST_STORAGE: {{ .Values.data.storageHost  | quote }}
  DES_SERVICE_HOST_COMPLIANCE: {{ .Values.data.legalHost  | quote }}
  SEISTORE_DES_TARGET_AUDIENCE: {{ .Values.data.googleAudiences  | quote }}
  SERVICE_CLOUD_PROJECT: {{ .Values.data.serviceCloudProject  | quote }}
  APP_ENVIRONMENT_IDENTIFIER: {{ .Values.data.appEnvironmentIdentifier  | quote }}
  IMP_SERVICE_ACCOUNT_SIGNER: {{ .Values.data.impServiceAccountSigner  | quote }}
  DES_SERVICE_HOST_ENTITLEMENT: {{ .Values.data.entitlementsHost  | quote }}
  SEISTORE_DES_APPKEY: {{ .Values.data.seistoreDesAppkey  | quote }}
  DES_REDIS_INSTANCE_ADDRESS: {{ .Values.data.redisDdmsHost  | quote }}
  DES_REDIS_INSTANCE_PORT: {{ .Values.data.redisPort  | quote }}
