apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.conf.appName }}"
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: "{{ .Values.conf.appName }}"
    service: "{{ .Values.conf.appName }}"
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      name: http
  selector:
    app: "{{ .Values.conf.appName }}"
