apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.conf.appName  | quote }}
  namespace: {{ .Release.Namespace  | quote }}
spec:
  hosts:
    - "*"
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/seismic-store-filemetadata"
      route:
        - destination:
            port:
              number: 80
            host: {{printf "%s.%s.svc.cluster.local" .Values.conf.appName .Release.Namespace | quote }}
