parameters:
  providerName: ""
  osdu_commit: ''
steps:
  - template: build-runtime-image.yml
    parameters:
      providerName: ${{ parameters.providerName }}
  - template: publish-build-artifact.yml
    parameters:
      providerName: ${{ parameters.providerName }}
