apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Release.Name }}-jwt-authz
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  action: DENY
  rules:
    - from:
        - source:
            notRequestPrincipals: ["*"]
      to:
        - operation:
            notPaths: ["/","*/index.html",
                       "*/v2/api-docs",
                       "*/actuator/health", "*/health",
                       "*/configuration/ui","*/configuration/security",
                       "{{ .Values.configEnv.sdmsPrefix }}/swagger-ui.html*"]
