apiVersion: v1
kind: ConfigMap
metadata:
  name: seistore-svc-properties
  namespace: {{ .Values.global.namespace }}
data:
  CLOUDPROVIDER: {{ .Values.configEnv.cloudProvider }}
  DES_SERVICE_HOST: https://{{ .Values.configEnv.desServiceHost }}
  REDIS_INSTANCE_PORT: "{{ .Values.configEnv.redisInstancePort }}"
  APP_ENVIRONMENT_IDENTIFIER: {{ .Values.configEnv.appEnvironmentIdentifier }}
  PORT: "{{ .Values.configEnv.port }}"
  SDMS_PREFIX: "{{ .Values.configEnv.sdmsPrefix }}"
