steps:
        - id: "builder"
          name: "gcr.io/cloud-builders/docker"
          args:
                  [
                          "build",
                          "-t",
                          "gcr.io/$PROJECT_ID/${_APPLICATION_NAME}/${_GC_SERVICE}-${_PROVIDER_NAME}-builder:local",
                          "-f",
                          "docker/builder.Dockerfile",
                          ".",
                  ]
          waitFor: ["-"]

        - id: "runtime"
          name: "gcr.io/cloud-builders/docker"
          args:
                  [
                          "build",
                          "--build-arg",
                          "docker_builder_image=gcr.io/$PROJECT_ID/${_APPLICATION_NAME}/${_GC_SERVICE}-${_PROVIDER_NAME}-builder:local",
                          "--build-arg",
                          "PORT=${_PORT}",
                          "-t",
                          "gcr.io/$PROJECT_ID/${_APPLICATION_NAME}/${_GC_SERVICE}-${_PROVIDER_NAME}:$_SHORT_SHA",
                          "-t",
                          "gcr.io/$PROJECT_ID/${_APPLICATION_NAME}/${_GC_SERVICE}-${_PROVIDER_NAME}:latest",
                          "-f",
                          "docker/runtime.Dockerfile",
                          ".",
                  ]
          waitFor: ["builder"]

images:
        - "gcr.io/$PROJECT_ID/${_APPLICATION_NAME}/${_GC_SERVICE}-${_PROVIDER_NAME}"
