data:
  requestsCpu: "0.1"
  requestsMemory: "256M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "seismic-store"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "seismic-store-config"
  appName: "seismic-store"
  urlPrefix: "/api/seismic-store/v3"
  # onprem configuration
  database: "seismic-store-db-secret"
  keycloak: "seismic-store-keycloak-secret"
  minio: "seismic-store-minio-secret"
  onPremEnabled: false
  domain: ""

istio:
  proxyCPU: "50m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
