data:
  requests_cpu: "0.25"
  requests_memory: "256M"
  limits_cpu: "1"
  limits_memory: "1G"
  serviceAccountName: ""
  image: ""

conf:
  configmap: "seismic-store-filemetadata-config"
  app_name: "seismic-store-filemetadata"
