parameters:
  - name: osdu_commit
    displayName: OSDU Commit
    type: string
    default: 'master'

trigger:
  batch: true
  branches:
    exclude:
      - master
  paths:
    exclude:
      - /**/*.md
      - .gitignore
      - /docs

resources:
  repositories:
    - repository: FluxRepo
      type: git
      name: k8-gitops-manifests
      ref: trunk

variables:
  - group: 'Azure - OSDU'
  - name: serviceName
    value: "seismic-dms-file-metadata-service"
  - name: environmentPrefix
    value: "seismicfilemeta"
  - name: chartPath
    value: "devops/azure/chart"
  - name: valuesFile
    value: "devops/azure/chart/helm-config.yaml"
  - name: 'MANIFEST_REPO'
    value: $[ resources.repositories['FluxRepo'].name ]
  - name: isGitlab
    value: false

stages:

  - template: template/build-stage.yml
    parameters:
      osdu_commit: ${{ parameters.osdu_commit }}
      serviceName: ${{ variables.serviceName }}
      providers:
        - name: Azure
  - template: template/deploy-stage.yml
    parameters:
      serviceName: ${{ variables.serviceName }}
      environmentPrefix: ${{ variables.environmentPrefix }}
      osdu_commit: ${{ parameters.osdu_commit }}
      installRequirements: false
      providers:
        - name: Azure
          environments:
            - name: 'dev'
              performE2Etests: false
              fluxEnabled: true
            - name: 'qa'
              performE2Etests: false
              fluxEnabled: true

  - template: template/change-management.yml
    parameters:
      serviceName: ${{ variables.serviceName }}
      environment: 'slbprd'
      provider: 'Azure'
      type: 'Internal'

  - template: template/deploy-stage-production.yml
    parameters:
      serviceName: ${{ variables.serviceName }}
      environmentPrefix: ${{ variables.environmentPrefix }}
      type: 'Internal'
      environmentDependsOn: 'slbprd'
      installRequirements: false
      providers:
        - name: Azure
          environments:
            - name: 'weu'
              performE2Etests: false
              fluxEnabled: true