aws-containerize:
  needs: []
  script:
      echo 'empty'
  only:
      - $DISABLED == 'true'
  
aws-update-helm:
  script:
      echo 'empty'
  only:
      - $DISABLED == 'true'

aws-update-tf:
  script:
      echo 'empty'
  only:
      - $DISABLED == 'true'
  
.aws-containerize:
  extends:
    - .aws    
    - .aws_common_variables
    - .aws_variables
  stage: containerize
  only:
    variables:
      - $AWS == '1'

.aws-update-helm:
  extends:
    - .aws
    - .aws_variables
    - .aws_common_variables
  stage: deploy
  retry: 1
  only:
    variables:
      - $AWS_SKIP_DEPLOY != 'true' && $AWS == '1' && $AWS_DEPLOY_TARGET == 'HELM'

.aws-update-tf:
  extends:
    - .aws
    - .aws_variables
    - .aws_common_variables
  stage: deploy
  retry: 1
  only:
    variables:
      - $AWS_SKIP_DEPLOY != 'true' && $AWS == '1' && $AWS_DEPLOY_TARGET == 'TF'