include:

  # azure-global
  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: release/0.16

  - local: "devops/osdu/cloud-providers/azure-common-pipeline.yml"
