# Copyright 2020 Google LLC
# Copyright 2017-2019, Schlumberger
# Copyright 2020 EPAM
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Global Protected Variables:
#
# OSDU_GCP
# OSDU_GCP_DEPLOY_FILE
# OSDU_GCP_SERVICE_ACCOUNT
# OSDU_GCP_INTEGRATION_TESTER
# OSDU_GCP_NO_DATA_ACCESS_TESTER

.osdu-gcp-variables:
  variables:
    # services' urls
    OSDU_GCP_STORAGE_HOSTNAME: community.osdu-gcp.go3-nrg.projects.epam.com
    OSDU_GCP_LEGALTAG_API: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/legal/v1
    OSDU_GCP_CRS_API: https://crs-converter-attcrcktoa-uc.a.run.app/api/crs/v2
    OSDU_GCP_REGISTER_URL: https://os-register-attcrcktoa-uc.a.run.app/
    OSDU_GCP_ENTITLEMENTS_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/entitlements/v2/
    OSDU_GCP_ENTITLEMENTS_V2_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/entitlements/v2/
    OSDU_GCP_ENTITLEMENTS_V2_BASE_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/api
    OSDU_GCP_AUTHORIZE_API: https://community.osdu-gcp.go3-nrg.projects.epam.com/entitlements/v2/
    OSDU_GCP_STORAGE_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/storage/v2/
    OSDU_GCP_RECORDS_ROOT_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/storage/v2/
    OSDU_GCP_LEGAL_HOST_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/legal/v1/
    OSDU_GCP_LEGAL_HOSTNAME: https://community.osdu-gcp.go3-nrg.projects.epam.com/
    OSDU_GCP_AIRFLOW_URL: https://y38fc16b71c3f21fbp-tp.appspot.com/
    OSDU_GCP_DELIVERY_SERVICE_URL: https://os-delivery-attcrcktoa-uc.a.run.app/api/delivery/v2/
    OSDU_GCP_INGEST_HOST: https://os-ingest-attcrcktoa-uc.a.run.app/
    OSDU_GCP_WORKFLOW_SERVICE_URL: https://os-workflow-attcrcktoa-uc.a.run.app/api/workflow/
    OSDU_GCP_SEARCH_HOST: https://os-search-attcrcktoa-uc.a.run.app/api/search/v2/
    OSDU_GCP_BACKUP_HOST: https://backup-attcrcktoa-uc.a.run.app
    OSDU_GCP_SEARCH_QUERY_URL: https://os-search-attcrcktoa-uc.a.run.app/api/search/v2/query/
    OSDU_GCP_INDEXER_HOST: https://community.osdu-gcp.go3-nrg.projects.epam.com/
    OSDU_GCP_INDEXER_HOST_SEARCH: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/indexer/v2/
    OSDU_GCP_FILE_URL: https://os-file-attcrcktoa-uc.a.run.app
    OSDU_GCP_NOTIFICATION_URL: https://os-notification-attcrcktoa-uc.a.run.app/api/notification/v1/
    OSDU_GCP_STORAGE_QUERY_RECORD_HOST: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/storage/v2/query/records
    OSDU_GCP_STORAGE_SCHEMA_HOST: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/storage/v2/schemas
    OSDU_GCP_STORAGE_QUERY_RECORD_FOR_CONVERSION_HOST: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/storage/v2/query/records:batch
    OSDU_GCP_INDEXER_QUEUE_HOST: https://indexer-queue-attcrcktoa-uc.a.run.app/api/indexer/v1/_dps/task-handlers/enqueue
    OSDU_GCP_UNIT_HOSTNAME: os-unit-attcrcktoa-uc.a.run.app
    OSDU_GCP_CRS_CONVERTER_HOSTNAME: crs-converter-attcrcktoa-uc.a.run.app
    OSDU_GCP_CRS_CATALOG_HOSTNAME: os-crs-catalog-attcrcktoa-uc.a.run.app
    OSDU_GCP_SCHEMA_URL: https://os-schema-attcrcktoa-uc.a.run.app
    OSDU_GCP_DATASET_URL: https://os-dataset-attcrcktoa-uc.a.run.app/api/dataset/v1/
    OSDU_GCP_PARTITION_API: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/partition/v1/
    OSDU_GCP_POLICY_API: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/policy/v1/
    OSDU_GCP_LOCAL_IMAGE_TAG_SHA: $CI_REGISTRY_IMAGE/osdu-gcp:$CI_COMMIT_SHORT_SHA
    REDIS_GROUP_HOST: 10.234.198.27
    REDIS_SEARCH_HOST: 10.99.138.107
    REDIS_STORAGE_HOST: 10.16.59.203
    REDIS_SYNC_HOST: 10.116.62.35
    OSDU_GCP_REDIS_SEARCH_PORT: 6379
    OSDU_GCP_SPRING_PROFILES_ACTIVE: dev
    OSDU_GCP_INDEXER_QUEUE_CLOUDTASK_NAME: os-indexer-queue-osdu
    # variables for unit deployment
    OSDU_GCP_UNIT_CATALOG_BUCKET: nice-etching-277309-unit-catalog-bucket
    # common variables
    OSDU_GCP_CLOUDRUN_REGION: us-central1
    OSDU_GCP_PROJECT: nice-etching-277309
    OSDU_GCP_VPC_CONNECTOR: osdu-connector
    OSDU_GCP_PORT: 8080
    #variables for seismic-store deployment
    OSDU_GCP_CLOUD_PROVIDER: google
    OSDU_GCP_IMP_SERVICE_ACCOUNT_SIGNER: unknown
    OSDU_GCP_SEISTORE_DES_APPKEY: na
    OSDU_GCP_DES_REDIS_INSTANCE_ADDRESS: 10.93.210.3
    OSDU_GCP_DES_REDIS_INSTANCE_PORT: 6379
    OSDU_GCP_LOCKSMAP_REDIS_INSTANCE_ADDRESS: 10.93.210.3
    OSDU_GCP_LOCKSMAP_REDIS_INSTANCE_PORT: 6379
    # variables for WKS service:
    OSDU_GCP_WKS_SEARCH_API: https://os-search-attcrcktoa-uc.a.run.app/api/search/v2
    OSDU_GCP_WKS_STORAGE_API: https://community.osdu-gcp.go3-nrg.projects.epam.com/api/storage/v2
    OSDU_GCP_WKS_SCHEMA_API: https://os-schema-attcrcktoa-uc.a.run.app/api/schema-service/v1
    # common variables for tests
    GOOGLE_AUDIENCE: 689762842995-pv217jo3k8j803kk6gqf52qb5amos3a9.apps.googleusercontent.com
    DOMAIN: osdu-gcp.go3-nrg.projects.epam.com
    LEGAL_TAG: osdu-demo-legaltag
    OTHER_RELEVANT_DATA_COUNTRIES: US
    DEFAULT_DATA_PARTITION_ID_TENANT1: osdu
    GCLOUD_PROJECT: nice-etching-277309
    # variables for storage tests
    TENANT_NAME: osdu
    # variables for workflow tests
    OSDU_GCP_ENTITLEMENTS_APPKEY: workflow-service
    FINISHED_WORKFLOW_ID: fad778da-fbc4-4261-8b3e-deb48be44969
    OSDU_GCP_TEST_DAG_NAME: airflow_monitoring
    # variables for ingestion tests
    TEST_OSDU_FILE_PATH: gs://nice-etching-277309-file/r1/data/provided/well-logs/1013_akm11_1978_comp.las
    # variables for file deployment and tests
    OSDU_GCP_DATASTORE_NAMESPACE: osdu-namespace
    FILE_BUCKET: nice-etching-277309-file
    ACL_OWNERS: data.default.owners
    ACL_VIEWERS: data.default.viewers
    TARGET_AUDIENCE: 689762842995-pv217jo3k8j803kk6gqf52qb5amos3a9.apps.googleusercontent.com
    DATA_PARTITION_ID: osdu
    USER_ID: common-user
    TIME_ZONE: UTC+0
    # variables for delivery tests
    ENTITLEMENTS_DOMAIN: osdu-gcp.go3-nrg.projects.epam.com
    TENANT: osdu
    #DEFAULT_DATA_PARTITION_ID_TENANT2: osdu
    INTEGRATION_TEST_AUDIENCE: 689762842995-pv217jo3k8j803kk6gqf52qb5amos3a9.apps.googleusercontent.com
    # variables for register tests, and deployment
    SERVICE_IDENTITY: osdu-gcp-sa
    RECORDS_CHANGE_PUBSUB_ENDPOINT: https://os-notification-attcrcktoa-uc.a.run.app/api/notification/v1/push-handlers/records-changed
    CRON_JOB_EXPECTED_IP: 0:0:0:0:0:0:0:1
    SUBSCRIBER_PRIVATE_KEY_ID: $OSDU_GCP_SUBSCRIBER_PRIVATE_KEY_ID
    SUBSCRIBER_SECRET: $OSDU_GCP_SUBSCRIBER_SECRET
    SUBSCRIPTION_ID: $OSDU_GCP_REGISTER_SUBSCRIPTION_ID
    REGISTER_CUSTOM_PUSH_URL: https://os-register-attcrcktoa-uc.a.run.app/api/register/v1/test/challenge/1
    CLIENT_TENANT: nonexistenttenant
    OSDU_TENANT: osdu
    REGISTER_BASE_URL: https://os-register-attcrcktoa-uc.a.run.app/
    ENVIRONMENT: dev
    # variables for notification tests
    HMAC_SECRET: $OSDU_GCP_SUBSCRIBER_SECRET
    REGISTER_CUSTOM_PUSH_URL_HMAC: https://os-register-attcrcktoa-uc.a.run.app/api/register/v1/test/challenge/hmac-integration-test
    TOPIC_ID: records-changed
    NOTIFICATION_BASE_URL: $OSDU_GCP_NOTIFICATION_URL
    # variables for legal tests
    MY_TENANT_PROJECT: osdu
    MY_TENANT: osdu
    ENABLE_FULL_BUCKET_NAME: "true"
    SKIP_HTTP_TESTS: "true"
    # variables for search tests
    DATA_GROUP: osdu
    ENTITLEMENTS_HOST: $OSDU_GCP_ENTITLEMENTS_URL
    ELASTIC_PASSWORD: $OSDU_GCP_ELASTIC_PASSWORD
    ELASTIC_USER_NAME: $OSDU_GCP_ELASTIC_USER
    ELASTIC_HOST: $OSDU_GCP_ELASTIC_HOST
    ELASTIC_PORT: $OSDU_GCP_ELASTIC_PORT
    DATA_PARTITION_ID_TENANT1: osdu
    # variables for schema tests
    VENDOR: $OSDU_GCP_VENDOR
    HOST: $OSDU_GCP_SCHEMA_URL
    PRIVATE_TENANT1: osdu
    PRIVATE_TENANT2: osdu
    SHARED_TENANT: osdu
    # variables for partition tests
    PARTITION_BASE_URL: https://community.osdu-gcp.go3-nrg.projects.epam.com/
    # variables for backup tests
    BACKUP_SERVICE_HOST: $OSDU_GCP_BACKUP_HOST
    OSDU_GCP_HELM_PACKAGE_CHARTS: "app/sdms/devops/gcp/deploy app/sdms/devops/gcp/configmap"
    
